version: '3.8'

services:
  db:
    image: postgres:13
    container_name: test_case_db
    environment:
      POSTGRES_USER: username123
      POSTGRES_PASSWORD: username123
      POSTGRES_DB: test_case_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local